### ISSUE TITLE
Task 1.3: Understand Bark

### ISSUE THREAD

**Issue by MarcelBruckner** [GAIL-4-BARK/bark-ml#12]
#2 

Goal:
- Extract expert trajectories from PPO/etc. / From Interaction dataset
- Build / debug system
- Testing environment
- Do tutorials
- https://bark-simulator.readthedocs.io/en/latest/agent_components.html

**Comment by Brucknem** [comment]
#2

**Comment by Brucknem** [comment]
Goal:
- **Extract expert trajectories** from PPO/etc. / From Interaction dataset
- Build / debug system

**Comment by MarcelBruckner** [comment]
## Subtasks 
- [ ] Understand how agents perceives world (Observed world)
- [ ] Train PPO/SAC agent to generate trajectories
- [ ] Get expert trajectories from bark #19
- [ ] How to query trajectories from interaction dataset 
- [ ] Get format of bark trajectories to then transfer to gail 
- [ ] Replace gym environment with bark
- [ ] Understand how agents acts in world

**Comment by marvinlue** [comment]
Open Issues:
* Set-up VS-Code Debugger
First steps:
1) Add configuration file in vs code and select "Python: Current File"
2) Select venv interpreter once venv is activated by (source dev_......sh) with short-cut:
Ctrl+Shift+p -> click "Python: Select Interpreter"
3) Add bark directory to pythonpath for module import:
Add in config file under env - pythonpath ":${workspaceFolder}"

!!! But still cant import/ work with modules from .cpp/.hpp !!!
-> for example od8_const_vel_one_agent.py:
can not load "from bark.commons import Params" in parameters.py
